"""empty message

Revision ID: ce7085e94200
Revises: c146efd5d3c8
Create Date: 2022-04-21 12:02:54.007018

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ce7085e94200'
down_revision = 'c146efd5d3c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_notificacao', sa.Column('tipo', sa.String(), nullable=True))
    op.add_column('tb_notificacao', sa.Column('json_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tb_notificacao', 'json_details')
    op.drop_column('tb_notificacao', 'tipo')
    # ### end Alembic commands ###
